from ast_nodes.alloc_lang_primitives import *
from ast_nodes.alloc_lang_aggregate  import *
from ast_nodes.alloc_lang_discard    import *
from ast_nodes.alloc_lang_binops     import *
from ast_nodes.alloc_lang_blocks     import *
from ast_nodes.alloc_lang_assess     import *
from ast_nodes.alloc_lang_alloc      import *
from ast_nodes.alloc_lang_scope      import *
from ast_nodes.alloc_lang_set        import *